---PRIMEIRO SEMESTRE-----------------------------------------------
INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('COMUNICAÇÃO E EXPRESSÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('FUNDAMENTOS DE BANCO DE DADOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('INTRODUÇÃO Á INTERNET DAS COISAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('LINGUAGEM DE PROGRAMAÇÃO I', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('LOGICA DE PROGRAMAÇÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('MATEMATICA APLICADA', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

-- SEGUNDO SEMESTRE------------------------------------------------------

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('AMBIENTE DE DESENVOLVIMENTO E OPERAÇÃO ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)


INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('ENGANHARIA DE SOFTWARE ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('GESTÃO DE PROJETOS ', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('LINGUAGEM DE PROGRAMAÇÃO II ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('LINGUAGEM SQL ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('LIBRAS ', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('SOCIEDADE E SUSTENTABILIDADE ', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('TECNOLOGIA WEB ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

-- TERCEIRO SEMESTRE---------------------------------------------------

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('ANÁLISE E MODELAGEM DE SISTEMAS ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('DESENVOLVIMENTO DE APLICAÇÕES DISTRIBUÍDAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('ESTRUTURA DE DADOS ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('INTERFACE HOMEM-COMPUTADOR ', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('ENGENHARIA DE REQUISITOS ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('OFICINA PROJETO EMPRESA 1-OPE1 ', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

--QUARTO SEMESTRE--------------------------------------------------

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('ARQUITETURA E PROJETO DE SISTEMAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('DESENVOLVIMENTO PARA DISPOSITIVOS MOVÉIS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('DESENVOLVIMENTO PARA INTERNET DAS COISAS ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('LEGISLAÇÃO E ÉTICA ', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('OFICINA PROJETO EMPRESA 2-OPE 2 ', 'PLANO DE ENSINO DA DISCIPLINA', 40, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)


INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('QUALIDADE DE SOFTWARE', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)


--QUINTO SEMESTRE--------------------------------------------------

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('BUSINESS AGILITY ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('DESENVOLVIMENTO DE SISTEMAS DE INFORMAÇÃO ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('STARTUP E INOVAÇÃO ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)


INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('TEORIA DA COMPUTAÇÃO', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

--SEXTO SEMESTRE---------------------------------------------------------

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('ANÁLISE DE VIABILIDADE DE PROJETOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('ANÁLISE EXPLORATÓRIA DE DADOS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('GESTÃO DE PROJETOS DE INOVAÇÃO ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('INTEGRAÇÃO E DESENVOLVIMENTO DE SISTEMAS', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

 --SETIMO SEMESTRE -----------------------------------------------------------

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('SEGURANÇA E AUDITORIA DE SISTEMAS ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('GESTÃO DE INFRAESTRUTURA DE TI ', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)


-- OITAVO SEMESTRE----------------------------------------------------------------

INSERT INTO DISCIPLINA (NOME, PLANODEENSINO, CARGAHORARIA, COMPETENCIAS, HABILIDADES, EMENTA, CONTEUDOPROGRAMATICO, BIBLIOGRAFIABASICA, BIBLIOGRAFIACOMPLEMENTAR, PERCENTUALPRATICO, PERCENTUALTEORICO, IDCOORDENADOR) VALUES
('GOVERNANÇA DE TI', 'PLANO DE ENSINO DA DISCIPLINA', 80, 'COMPETENCIAS DA DISCIPLINA',
'HABILIDADES DA DISCIPLINA', 'EMENTA DA DISCIPLINA', 'CONTEUDO DA DISCIPLINA', 'BIBLIOGRAFIA BÁSICA', 'BIBLIOGRAFIA COMPLEMENTAR',100,0,1)

